# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa48048cafeaffd7424b2b0eda7b8d4b45383456ae4ea6dfc5403476a0de004874d5f70f774df69066bf0a85148718ef1cdbc8c98b6e46a89bb9c73f02f235ab

test:
  secret_key_base: 76a547df3cba7dc68cd7cbd2cbdee3cc9c4d2de8fedd9f3bf5ebdaa1b036eda0bf4829c52ab96116430026bb45c45f3120fa1f1d2770d462d8d6aeb4bd34e297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
